export const userlist = [
  {
    id: 1,
    jobTitleName: 'IOS Developer',
    firstName: 'Romin',
    lastName: 'Irani',
    phoneNumber: '408-1234-567',
    emailAddress: 'romin.k.irani@gmail.com',
    profImg: '/images/pic1.png',
  },
  {
    id: 2,
    jobTitleName: 'Developer',
    firstName: 'Neil',
    lastName: 'Irani',
    phoneNumber: '408-111-1111',
    emailAddress: 'neilrirani@gmail.com',
    profImg: '/images/pic2.png',
  },
  {
    id: 3,
    jobTitleName: 'Fullstack Developer',
    firstName: 'Tom',
    lastName: 'Hanks',
    phoneNumber: '408-222-2222',
    emailAddress: 'tomhanks@gmail.com',
    profImg: '/images/pic3.png',
  },
  {
    id: 4,
    jobTitleName: 'Android Developer',
    firstName: 'Jane',
    lastName: 'Lane',
    phoneNumber: '476-997-2245',
    emailAddress: 'lane34@gmail.com',
    profImg: '/images/pic4.png',
  },
  {
    id: 5,
    jobTitleName: 'UI/UX Designer',
    firstName: 'Loren',
    lastName: 'Batz',
    phoneNumber: '346-629-9999',
    emailAddress: 'lorenbatz934@gmail.com',
    profImg: '/images/pic5.png',
  },
  {
    id: 6,
    jobTitleName: 'Frontend Developer',
    firstName: 'Winston',
    lastName: 'Conn',
    phoneNumber: '733-198-3477',
    emailAddress: 'iamwinston@gmail.com',
    profImg: '/images/pic6.png',
  },
];
