import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Assignment 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div className={styles.navbar}>
          <div>
            <h1>Canvas</h1>
          </div>
          <div className={styles.listItems}>
            <Link href="/">Home</Link>
            <Link href="/project">Project</Link>
            <Link href="/team">Our Team</Link>
          </div>
        </div>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.infosys.com/">Infosys!</a>
        </h1>
        <div className={styles.bannerDes}>
          <Image
            src="/images/Banner.png"
            height={280}
            width={600}
            alt="Profile Pic"
          />
          <p>
            Infosys Limited is an Indian multinational information technology
            company that provides business consulting, information technology
            and outsourcing services. The company was founded in Pune and is
            headquartered in Bangalore Infosys shares were listed on the Nasdaq
            stock exchange in 1999 as American depositary receipts (ADR). It
            became the first Indian company to be listed on Nasdaq. The share
            price surged to ₹8,100 (equivalent to ₹30,000 or US$370 in 2020) by
            1999, making it the costliest share on the market at the time. At
            that time, Infosys was among the 20 biggest companies by market
            capitalization on the Nasdaq.The ADR listing was shifted from Nasdaq
            to NYSE Euronext to give European investors better access to the
            company's shares.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
